import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { tmpDir, mockLogger } from './helpers.ts'
import { createDialecticSystem } from '../src/dialectic/index.js'

/**
 * Test Providers
 *
 * These mock providers capture LLM calls and return controlled responses
 * to test task guide behavior without making real API calls.
 */

/** Provider that captures all messages sent to it for verification */
class CaptureProvider {
  id = 'capture'
  models = ['capture']
  calls: Array<Array<{ role: string; content: string }>> = []

  async *complete(messages: unknown[], opts: unknown) {
    // Deep copy messages to prevent mutation
    this.calls.push(messages.map(m => {
      const msg = m as { role: string; content: string }
      return { role: msg.role, content: msg.content }
    }))
    yield { type: 'done' as const, model: (opts as { model?: string })?.model }
  }

  async countTokens() { return 0 }
  async ping() { return true }
}

/** Provider that simulates LLM-based task guide generation */
class SummarizerProvider {
  id = 'summarizer'
  models = ['gpt-5-mini', 'gemini-3-pro-high', 'k2p5']
  calls: Array<Array<{ role: string; content: string }>> = []

  async *complete(messages: unknown[], opts: unknown) {
    this.calls.push(messages.map(m => {
      const msg = m as { role: string; content: string }
      return { role: msg.role, content: msg.content }
    }))
    const prompt = String((messages[0] as { content?: string })?.content || '')

    // When prompted as a task summarizer, generate a guide
    if (prompt.includes('concise task summarizer')) {
      yield { type: 'token' as const, text: 'TASK GUIDE: Provide concise code examples where applicable.' }
      yield { type: 'done' as const, model: (opts as { model?: string })?.model }
      return
    }

    // Default response for dialectic analysis
    yield { type: 'token' as const, text: '{"branches": []}' }
    yield { type: 'done' as const, model: (opts as { model?: string })?.model }
  }

  async countTokens() { return 0 }
  async ping() { return true }
}

/** Provider that simulates LLM failures */
class FailingProvider {
  id = 'failing'
  models = ['failing']
  calls: Array<Array<{ role: string; content: string }>> = []
  failCount = 0
  currentCall = 0

  async *complete(messages: unknown[], opts: unknown) {
    this.currentCall++
    this.calls.push(messages.map(m => {
      const msg = m as { role: string; content: string }
      return { role: msg.role, content: msg.content }
    }))

    // Fail on the first N calls (task guide generation), succeed afterwards
    if (this.currentCall <= this.failCount) {
      throw new Error('LLM service unavailable')
    }

    yield { type: 'token' as const, text: '{"branches": []}' }
    yield { type: 'done' as const, model: (opts as { model?: string })?.model }
  }

  async countTokens() { return 0 }
  async ping() { return true }
}

/** Provider that simulates slow responses (for timeout testing) */
class SlowProvider {
  id = 'slow'
  models = ['slow']
  calls: Array<Array<{ role: string; content: string }>> = []
  delayMs: number

  constructor(delayMs: number) {
    this.delayMs = delayMs
  }

  async *complete(messages: unknown[], opts: unknown) {
    this.calls.push(messages.map(m => {
      const msg = m as { role: string; content: string }
      return { role: msg.role, content: msg.content }
    }))

    await new Promise(resolve => setTimeout(resolve, this.delayMs))

    yield { type: 'token' as const, text: 'TASK GUIDE: Generated after delay.' }
    yield { type: 'done' as const, model: (opts as { model?: string })?.model }
  }

  async countTokens() { return 0 }
  async ping() { return true }
}

/**
 * Dialectic Task Guide Tests
 *
 * The task guide feature provides a brief summary of the user's request
 * to help the dialectic trio (Yang, Yin, Serenity) understand what the
 * user needs. This improves the relevance of dialectic analysis by
 * giving observers clear context upfront.
 *
 * Two generation modes are supported:
 * - Heuristic: Fast template-based guide from the user message
 * - LLM: More nuanced guide generated by an LLM call
 */
describe('Dialectic Task Guide', () => {
  let homeTmp: ReturnType<typeof tmpDir>
  let originalHome: string | undefined

  beforeEach(() => {
    homeTmp = tmpDir()
    originalHome = process.env.HOME
    process.env.HOME = homeTmp.path
  })

  afterEach(() => {
    if (originalHome === undefined) delete process.env.HOME
    else process.env.HOME = originalHome
    homeTmp.cleanup()
  })

  /**
   * Heuristic Mode
   *
   * In heuristic mode, the task guide is generated by truncating and
   * wrapping the user's message in a template. This is fast and doesn't
   * require an additional LLM call.
   */
  describe('heuristic mode', () => {
    it('generates a task guide from the user message and includes it in dialectic prompts', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: true } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const userMessage = 'Please give a code example to parse JSON in Node.'
      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-1', 'turn-1', userMessage, ctx as unknown as import('@cassicore/foundation').YangContext)

      // The dialectic system should have been invoked
      expect(prov.calls.length).toBeGreaterThanOrEqual(1)

      // At least one call should include the task guide in the prompt
      const found = prov.calls.some((msgArr) =>
        String(msgArr[0]?.content || '').includes('TASK GUIDE')
      )
      expect(found).toBe(true)
    })

    it('truncates long user messages to 160 characters in the task guide', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: true } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      // Create a message longer than 160 characters with a unique prefix
      const uniquePrefix = 'XYZUNIQUE_'
      const longMessage = uniquePrefix + 'A'.repeat(200)
      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-1', 'turn-1', longMessage, ctx as unknown as import('@cassicore/foundation').YangContext)

      // Find the task guide in the calls
      const taskGuideCall = prov.calls.find((msgArr) =>
        String(msgArr[0]?.content || '').includes('TASK GUIDE')
      )
      expect(taskGuideCall).toBeDefined()

      // The guide should contain the unique prefix and 160-10=150 As
      const content = String(taskGuideCall![0]?.content || '')
      const guideMatch = content.match(/TASK GUIDE: Address the user's request: "([^"]+)"/)
      expect(guideMatch).toBeDefined()
      // Total guide content should be prefix + truncated message (capped at 160 chars)
      expect(guideMatch![1].length).toBeLessThanOrEqual(160)
      // Should include the unique prefix
      expect(guideMatch![1]).toContain(uniquePrefix)
    })

    it('preserves existing task guides in context without regenerating', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: true } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      // Provide a pre-existing task guide in context
      const existingGuide = 'TASK GUIDE: Custom guide from previous processing'
      const ctx = {
        recentMemories: [],
        availableTools: [],
        sessionHistory: [],
        taskGuide: existingGuide
      }
      await dialectic.processTurn('sess-1', 'turn-1', 'user message', ctx as unknown as import('@cassicore/foundation').YangContext)

      // Should still find the task guide in prompts
      const found = prov.calls.some((msgArr) =>
        String(msgArr[0]?.content || '').includes(existingGuide)
      )
      expect(found).toBe(true)
    })
  })

  /**
   * LLM Mode
   *
   * In LLM mode, the system makes an additional LLM call to generate
   * a more nuanced 1-3 sentence task guide. This provides better context
   * at the cost of an extra request.
   */
  describe('LLM mode', () => {
    it('generates task guides using an LLM call when configured', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'llm', enabled: true, timeoutMs: 2000 } })

      const prov = new SummarizerProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const userMessage = 'Can you provide a quick coding example for parsing CSV and some tips?'
      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-llm', 'turn-llm', userMessage, ctx as unknown as import('@cassicore/foundation').YangContext)

      // The summarizer should have been called for task guide generation
      // followed by dialectic analysis, so at least 2 calls
      expect(prov.calls.length).toBeGreaterThanOrEqual(2)

      // One of the calls should request task guide generation (system prompt)
      const summarizerCall = prov.calls.find((msgArr) =>
        String(msgArr[0]?.content || '').includes('concise task summarizer')
      )
      expect(summarizerCall).toBeDefined()

      // The generated guide should appear in subsequent dialectic calls
      const dialecticWithGuide = prov.calls.some((msgArr) =>
        String(msgArr[0]?.content || '').includes('TASK GUIDE: Provide concise code examples')
      )
      expect(dialecticWithGuide).toBe(true)
    })

    it('emits the generated task guide in stream start events', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'llm', enabled: true, timeoutMs: 2000 } })

      const prov = new SummarizerProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      let capturedTaskGuide: string | undefined = undefined
      dialectic.subscribeToStream('sess-stream', (ev: unknown) => {
        const event = ev as { stage: string; data?: { taskGuide?: string } }
        if (event.stage === 'start' && event.data?.taskGuide) {
          capturedTaskGuide = event.data.taskGuide
        }
      })

      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-stream', 'turn-stream', 'Test message', ctx as unknown as import('@cassicore/foundation').YangContext)

      expect(capturedTaskGuide).toBeTruthy()
      expect(capturedTaskGuide).toMatch(/^TASK GUIDE:/) 
    })

    it('falls back to heuristic mode when LLM generation times out', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'llm', enabled: true, timeoutMs: 100 } })

      // Provider that takes longer than the timeout
      const prov = new SlowProvider(500)
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      const userMessage = 'This is a test message for timeout scenario'

      // Should not throw - falls back gracefully
      await expect(
        dialectic.processTurn('sess-timeout', 'turn-timeout', userMessage, ctx as unknown as import('@cassicore/foundation').YangContext)
      ).resolves.toBeDefined()

      // Should still have made the LLM call attempt
      expect(prov.calls.length).toBeGreaterThanOrEqual(1)
    })

    it('falls back to heuristic mode when LLM generation fails', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'llm', enabled: true, timeoutMs: 2000 } })

      const prov = new FailingProvider()
      prov.failCount = 1 // Fail on first call (task guide generation)
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      const userMessage = 'Test message for failure scenario'

      // Should not throw - falls back gracefully
      const result = await dialectic.processTurn('sess-fail', 'turn-fail', userMessage, ctx as unknown as import('@cassicore/foundation').YangContext)
      expect(result).toBeDefined()

      // Should have attempted the task guide generation call
      expect(prov.calls.length).toBeGreaterThanOrEqual(1)
    })
  })

  /**
   * Configuration Edge Cases
   *
   * Tests for various configuration scenarios and edge cases.
   */
  describe('configuration edge cases', () => {
    it('does not generate task guides when the feature is disabled', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: false } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-disabled', 'turn-disabled', 'Test message', ctx as unknown as import('@cassicore/foundation').YangContext)

      // Should not contain any TASK GUIDE in the calls
      const hasTaskGuide = prov.calls.some((msgArr) =>
        String(msgArr[0]?.content || '').includes('TASK GUIDE')
      )
      expect(hasTaskGuide).toBe(false)
    })

    it('defaults to heuristic mode when mode is not specified', async () => {
      const logger = mockLogger()
      // enabled: true but no mode specified
      const dialectic = createDialecticSystem(logger, { taskGuide: { enabled: true } as { enabled: boolean; mode?: 'heuristic' | 'llm' } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const userMessage = 'Test message for default mode'
      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-default', 'turn-default', userMessage, ctx as unknown as import('@cassicore/foundation').YangContext)

      // Should generate a heuristic task guide
      const found = prov.calls.some((msgArr) =>
        String(msgArr[0]?.content || '').includes('TASK GUIDE')
      )
      expect(found).toBe(true)
    })

    it('uses default timeout of 3000ms when not specified in LLM mode', async () => {
      const logger = mockLogger()
      // LLM mode without explicit timeout
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'llm', enabled: true } })

      const prov = new SummarizerProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-default-timeout', 'turn-1', 'Test', ctx as unknown as import('@cassicore/foundation').YangContext)

      // Should complete successfully with default timeout
      expect(prov.calls.length).toBeGreaterThanOrEqual(1)
    })
  })

  /**
   * Input Edge Cases
   *
   * Tests for unusual or problematic input scenarios.
   */
  describe('input edge cases', () => {
    it('handles empty user messages gracefully', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: true } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-empty', 'turn-empty', '', ctx as unknown as import('@cassicore/foundation').YangContext)

      // Should not throw and should complete
      expect(prov.calls.length).toBeGreaterThanOrEqual(0)
    })

    it('handles user messages with special characters', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: true } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      const specialMessage = 'Test with "quotes", \n newlines, and emojis 🎉'
      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-special', 'turn-special', specialMessage, ctx as unknown as import('@cassicore/foundation').YangContext)

      // Should handle special characters without issues
      expect(prov.calls.length).toBeGreaterThanOrEqual(1)
    })

    it('handles very long user messages by truncating', async () => {
      const logger = mockLogger()
      const dialectic = createDialecticSystem(logger, { taskGuide: { mode: 'heuristic', enabled: true } })

      const prov = new CaptureProvider()
      dialectic.setProvider(prov as unknown as import('@cassicore/foundation').IProvider)

      // Message much longer than 160 characters with unique marker
      const uniqueMarker = 'TRUNC_TEST_'
      const veryLongMessage = uniqueMarker + 'B'.repeat(1000)
      const ctx = { recentMemories: [], availableTools: [], sessionHistory: [] }
      await dialectic.processTurn('sess-long', 'turn-long', veryLongMessage, ctx as unknown as import('@cassicore/foundation').YangContext)

      // Find the task guide in the calls
      const taskGuideCall = prov.calls.find((msgArr) =>
        String(msgArr[0]?.content || '').includes('TASK GUIDE')
      )
      expect(taskGuideCall).toBeDefined()

      // Verify truncation at 160 characters in the guide specifically
      const content = String(taskGuideCall![0]?.content || '')
      const guideMatch = content.match(/TASK GUIDE: Address the user's request: "([^"]+)"/)
      expect(guideMatch).toBeDefined()
      // Total length should be capped at 160 chars
      expect(guideMatch![1].length).toBeLessThanOrEqual(160)
      // Should still have the unique marker
      expect(guideMatch![1]).toContain(uniqueMarker)
    })
  })
})
