#!/usr/bin/env python3
"""
ManifoldCord — streaming-context resonant field architecture.

Reimagines MuonCord's context model: N is working-memory bandwidth
(window size), not context length.  Context length is emergent from
IIR dynamics (temporal memory) + pattern memory (compressed long-term
store).

Files of any length are processed in windows of N tokens, carrying
field state forward between windows.  Forward-only (no bidirectional)
halves kernel launches and resolves the ROCm AQLPacket crash.
"""

from typing import Optional, Tuple

import torch
import torch.nn.functional as F

from muon_cord import MuonCord


class ManifoldCord(MuonCord):
    """Streaming-context variant of MuonCord.

    N is the working-memory bandwidth (window size W), not the context
    length.  Context is streamed through windows; IIR state + pattern
    memory carry cross-window context.  Forward-only (no bidirectional)
    to halve kernel launches.

    Existing MuonCord checkpoints load directly (same architecture,
    backward readout heads present but unused).
    """

    def __init__(self, **kwargs):
        # Force forward-only — bidirectional is never used
        kwargs['bidirectional'] = False
        super().__init__(**kwargs)

    # ════════════════════════════════════════════════
    #  Streaming Generation
    # ════════════════════════════════════════════════

    def _process_seed_windows(self, seed: torch.Tensor, K_init: int) -> None:
        """Process seed through windows of size N, accumulating IIR state.

        Resets IIR state, resizes submodule buffers to batch=1, then iterates
        windows of N tokens over the seed, running K_init _unified_step calls
        per window with _clamp_iir_state safety.  Leaves IIR state in self.h1
        etc. ready for generation.
        """
        L = seed.numel()
        device = seed.device

        # ── Process seed through windows ──
        self.reset_iir_state()
        self.resonant_field.resize_buffers(1, device, self.h1.dtype)
        self.multi_scale_cord.resize_buffers(1, device, self.h1.dtype)
        self.tonic_phasic.resize_buffers(1)
        self._current_delta_rho = None
        self._current_delta_theta = None
        self._current_delta_gamma = None

        num_windows = max(1, (L + self.N - 1) // self.N)
        q_ema = self.Q_ema.detach()
        for wi in range(num_windows):
            start = wi * self.N
            end = min(start + self.N, L)
            chunk = seed[start:end]  # [chunk_len]

            # Pad to N if needed (last window may be partial)
            if chunk.numel() < self.N:
                pad = chunk[-1:].expand(self.N - chunk.numel())
                window = torch.cat([chunk, pad])
            else:
                window = chunk

            batch = window.unsqueeze(0)  # [1, N]

            # ── Settle: run K_init field steps to accumulate state ──
            psi_real, psi_imag = self.embed(batch)
            for _ in range(K_init):
                psi_real, psi_imag = self._evolve_one_step(
                    psi_real, psi_imag, q_ema, clamp_field=False)

    @torch.no_grad()
    def generate_from_stream(self,
                             seed: torch.Tensor,
                             max_new: int = 128,
                             temp: float = 0.8,
                             K_init: Optional[int] = None,
                             repetition_penalty: float = 1.2,
                             rep_window: int = 8,
                             top_k: Optional[int] = None,
                             ngram_block_size: int = 0
                             ) -> torch.Tensor:
        """Generate bytes from a seed of any length using streaming context.

        Processes the seed through windows of size N, accumulating field
        state across the entire seed.  Then generates max_new tokens
        autoregressively from the accumulated context.

        This is the streaming counterpart to generate_autoregressive —
        the seed can be arbitrarily long (processed in windows) rather
        than limited to a single N-token window.

        Args:
            seed: [L] or [1, L] byte tensor — can be any length.
            max_new: Number of tokens to generate.
            temp: Sampling temperature.
            K_init: Field steps per window during seed processing
                    (default: self.K_gen).
            repetition_penalty: Penalty factor for repeated tokens.
            rep_window: Window size for repetition penalty.
            top_k: Top-k sampling (disabled if None).
            ngram_block_size: N-gram blocking (disabled if 0).

        Returns:
            [max_new] generated byte tensor.
        """
        if K_init is None:
            K_init = self.K_gen
        device = seed.device
        self.eval()

        # ── Ensure seed is 1D ──
        if seed.ndim > 1:
            seed = seed.squeeze(0)
        L = seed.numel()

        self._process_seed_windows(seed, K_init)

        # ── Autoregressive generation ──
        # Build initial window from the last N-1 seed tokens + 1 placeholder
        if L >= self.N:
            window_list = list(seed[-self.N:].tolist())
        else:
            pad = seed[-1:].expand(self.N - L)
            window_list = list(torch.cat([seed, pad]).tolist())

        generated = []
        q_ema = self.Q_ema.detach()
        for _ in range(max_new):
            batch = torch.tensor(window_list, dtype=torch.long,
                                 device=device).unsqueeze(0)
            psi_real, psi_imag = self.embed(batch)
            psi_real, psi_imag = self._evolve_one_step(
                psi_real, psi_imag, q_ema, clamp_field=True)

            logits = self.readout_positions(psi_real, psi_imag)[0, -1, :] / max(temp, 1e-6)

            next_byte = self._sample_with_penalties(
                logits, generated,
                repetition_penalty, rep_window, ngram_block_size, top_k)
            generated.append(next_byte)
            window_list.pop(0)
            window_list.append(next_byte)

        return torch.tensor(generated, dtype=torch.long, device=device)

    @torch.no_grad()
    def generate_parallel_stream(self,
                                 seed: torch.Tensor,
                                 max_new: int = 128,
                                 temp: float = 0.8,
                                 K_init: Optional[int] = None,
                                 context_frac: float = 0.5,
                                 refine_passes: int = 0,
                                 repetition_penalty: float = 1.2,
                                 rep_window: int = 8,
                                 top_k: Optional[int] = None,
                                 ngram_block_size: int = 0,
                                 ripple_scale: float = 0.062) -> torch.Tensor:
        """Generate bytes in parallel blocks from a seed of any length.

        Processes the seed through streaming windows (accumulating IIR state),
        then generates max_new tokens in iterative parallel blocks.  Each block
        fills (N - suffix_len) positions simultaneously via field inpainting:
        the context suffix is placed at the start of an N-position window, the
        remaining positions are zero-filled, K_init field steps propagate
        information from context into the empty positions via spatial coupling
        and attention, then all new positions are read out and sampled together.

        This is the streaming counterpart to generate_parallel — the seed can
        be arbitrarily long (processed in windows) and max_new can exceed N
        (handled via multiple blocks).

        Args:
            seed: [L] or [1, L] byte tensor — can be any length.
            max_new: Number of tokens to generate.
            temp: Sampling temperature.
            K_init: Field steps per window during seed processing and per block
                    (default: self.K_gen).
            context_frac: Fraction of the N-position window used as context
                          suffix.  The remaining (1 - context_frac) positions
                          are generated in parallel per block.  Default 0.5.
            refine_passes: Additional evolution+resample passes per block to
                           improve coherence (0 = single pass).
            repetition_penalty: Penalty factor for repeated tokens.
            rep_window: Window size for repetition penalty.
            top_k: Top-k sampling (disabled if None).
            ngram_block_size: N-gram blocking (disabled if 0).

        Returns:
            [max_new] generated byte tensor.
        """
        if K_init is None:
            # Qi pool gates evolution depth: charged → richer generation
            pool_frac = self.qi_pool.item() / (self.qi_pool_peak.item() + 1e-8)
            K_init = max(1, int(self.K_gen * (0.5 + pool_frac)))
        device = seed.device
        self.eval()

        # ── Ensure seed is 1D ──
        if seed.ndim > 1:
            seed = seed.squeeze(0)

        if max_new <= 0:
            return torch.tensor([], dtype=torch.long, device=device)

        # ── Process seed through streaming windows ──
        self._process_seed_windows(seed, K_init)

        # ── Block parameters ──
        suffix_len = int(self.N * context_frac)
        suffix_len = min(suffix_len, self.N - 1)  # ensure at least 1 generation slot
        block_size = self.N - suffix_len

        # ── Build initial context from seed suffix ──
        L = seed.numel()
        if L >= suffix_len:
            context = list(seed[-suffix_len:].tolist())
        else:
            pad = seed[-1:].expand(suffix_len - L)
            context = list(torch.cat([seed, pad]).tolist())

        generated: list = []

        q_ema = self.Q_ema.detach()
        # ════════════════════════════════════════════════
        #  Block generation loop
        # ════════════════════════════════════════════════
        while len(generated) < max_new:
            # ── Build window: context suffix + zero-fill ──
            window = context[-suffix_len:] + [0] * block_size

            # ── Local: evolve field from a window list ──
            def _evolve_block(window_tokens):
                batch = torch.tensor(window_tokens, dtype=torch.long, device=device).unsqueeze(0)
                psi_real, psi_imag = self.embed(batch)
                for step in range(K_init):
                    psi_real, psi_imag = self._evolve_one_step(
                        psi_real, psi_imag, q_ema, clamp_field=True)
                    # After half the settling steps, add ripple for structured exploration
                    if (step >= K_init // 2 and ripple_scale > 0
                            and self.qi_quality_ema.item() < 0.8):
                        rip_re, rip_im = self._compute_ripple(
                            psi_real, psi_imag, probe_scale=0.01)
                        psi_real = psi_real + ripple_scale * rip_re
                        psi_imag = psi_imag + ripple_scale * rip_im
                return psi_real, psi_imag

            # ── Evolve K_init steps (carries IIR state forward) ──
            psi_real, psi_imag = _evolve_block(window)

            # ── Readout all positions ──
            logits_all = self.readout_positions(psi_real, psi_imag)[0] / max(temp, 1e-6)

            # ── Optional refinement passes ──
            for _ in range(refine_passes):
                # Provisional sample (no penalties) to fill empty positions
                provisional = []
                for pos in range(suffix_len, self.N):
                    probs = F.softmax(logits_all[pos], dim=-1)
                    provisional.append(torch.multinomial(probs, 1).item())
                # Fill into window and re-evolve
                for i, tok in enumerate(provisional):
                    window[suffix_len + i] = tok
                psi_real, psi_imag = _evolve_block(window)
                logits_all = self.readout_positions(psi_real, psi_imag)[0] / max(temp, 1e-6)

            # ── Sample positions [suffix_len, N) with penalties ──
            block_tokens = []
            for pos in range(suffix_len, self.N):
                tok = self._sample_with_penalties(
                    logits_all[pos], generated,
                    repetition_penalty, rep_window, ngram_block_size, top_k)
                block_tokens.append(tok)

            # ── Take only what we need ──
            remaining = min(block_size, max_new - len(generated))
            new_tokens = block_tokens[:remaining]
            generated.extend(new_tokens)
            context.extend(new_tokens)

        return torch.tensor(generated[:max_new], dtype=torch.long, device=device)

# ════════════════════════════════════════════════
#  Smoke test
# ════════════════════════════════════════════════

if __name__ == '__main__':
    import os
    os.environ.setdefault('PYTORCH_HIP_ALLOC_CONF', 'expandable_segments:True')
    os.environ.setdefault('HSA_ENABLE_SDMA', '0')
    if torch.cuda.device_count() > 1:
        os.environ.setdefault('CUDA_VISIBLE_DEVICES', '1')

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Device: {device}')
    if device.type == 'cuda':
        print(f'  GPU: {torch.cuda.get_device_name(device)}')

    m = ManifoldCord(N=128, d=256).to(device)
    x = torch.randint(0, 256, (4, 128)).to(device)

    # Test streaming: process 4 windows with state carry-forward
    print('--- Streaming test ---')
    for i in range(4):
        xi = x.clone()
        loss, info = m.training_loss(xi, no_reset=(i > 0))
        assert not torch.isnan(loss), f'NaN at window {i}'
        print(f'  Window {i}: loss={loss.item():.4f}, qi={info.get("qi_mean", info.get("Q_mean", 0)):.3f}, '
              f'q_ema={info.get("qi_quality_ema", 0):.3f}')
    print(f'  Streaming OK')

    # Test generation from stream
    print('--- Generation test ---')
    seed = torch.randint(0, 256, (256,)).to(device)  # 2 windows worth
    gen = m.generate_from_stream(seed, max_new=64, temp=0.8)
    assert gen.shape[0] == 64, f'Expected 64 tokens, got {gen.shape[0]}'
    print(f'  Generation OK: {gen.shape}, tokens: {gen[:16].tolist()}...')

    # Test generation from short seed (< N)
    print('--- Short seed test ---')
    short_seed = torch.randint(0, 256, (64,)).to(device)
    gen2 = m.generate_from_stream(short_seed, max_new=32, temp=0.8)
    assert gen2.shape[0] == 32
    print(f'  Short seed OK: {gen2.shape}')

    # Test parallel block generation from stream
    print('--- Parallel generation test ---')
    gen_par = m.generate_parallel_stream(seed, max_new=128, temp=0.8)
    assert gen_par.shape[0] == 128, f'Expected 128 tokens, got {gen_par.shape[0]}'
    print(f'  Parallel gen OK: {gen_par.shape}, tokens: {gen_par[:16].tolist()}...')

    # Test parallel gen with short seed
    gen_par2 = m.generate_parallel_stream(short_seed, max_new=64, temp=0.8)
    assert gen_par2.shape[0] == 64
    print(f'  Parallel short seed OK: {gen_par2.shape}')

    # Test parallel gen with long seed (3 windows worth)
    long_seed = torch.randint(0, 256, (384,)).to(device)
    gen_par3 = m.generate_parallel_stream(long_seed, max_new=128, temp=0.8)
    assert gen_par3.shape[0] == 128
    print(f'  Parallel long seed OK: {gen_par3.shape}')

    # Test masked prediction training
    print('--- Masked prediction test ---')
    m.train()
    loss_masked, info_masked = m.training_loss(x, mask_ratio=0.35)
    assert not torch.isnan(loss_masked), 'Masked loss is NaN'
    assert info_masked['mask_count'] > 0, 'No positions were masked'
    print(f'  Masked loss OK: {loss_masked.item():.4f}, '
          f'mask_count={info_masked["mask_count"]}')

    # Test standard (mask_ratio=0) still works
    loss_std, info_std = m.training_loss(x, mask_ratio=0.0)
    assert not torch.isnan(loss_std), 'Standard loss is NaN'
    assert 'mask_count' not in info_std, 'mask_count should not exist in standard mode'
    print(f'  Standard loss OK: {loss_std.item():.4f}')

    # Test that mask_embed is a learnable parameter
    assert m.mask_embed.requires_grad, 'mask_embed should require grad'
    print(f'  mask_embed shape: {m.mask_embed.shape}, requires_grad={m.mask_embed.requires_grad}')

    # Test new Qi diagnostics
    print('--- Qi diagnostics test ---')
    assert 'qi_mean' in info_std or 'Q_mean' in info_std, 'Missing Qi diagnostics'
    print(f'  Qi diagnostics OK: qi_mean={info_std.get("qi_mean", info_std.get("Q_mean", "N/A"))}')

    # Test chakra alignment projections exist
    print('--- Chakra projection test ---')
    assert hasattr(m, 'chakra_proj'), 'Missing chakra_proj'
    assert len(m.chakra_proj) == 13, f'Expected 13 chakra projections, got {len(m.chakra_proj)}'
    print(f'  Chakra projections OK: {len(m.chakra_proj)} bands → {m.d_chakra_shared}d')

    n_p = sum(p.numel() for p in m.parameters())
    print(f'  Params: {n_p:,}')
    print('All tests passed.')
