from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import subprocess
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

ROOT = Path(__file__).resolve().parent
SCRIPT = ROOT / "run_cassi_qi_artifact_cleanup.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("artifact_cleanup_under_test", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


cleanup = _load_module()


def _canonical(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _domain_hash(value: Any, domain: str) -> str:
    body = _canonical(value)
    prefix = domain.encode("utf-8")
    return _sha(len(prefix).to_bytes(8, "big") + prefix + len(body).to_bytes(8, "big") + body)


def _self_hashed(schema: str, body: dict[str, Any], *, field: str = "self_sha256", domain: str | None = None) -> dict[str, Any]:
    result = {"schema": schema, **body}
    hash_body = {key: value for key, value in result.items() if key != field}
    result[field] = _domain_hash(hash_body, domain or schema) if domain else _sha(_canonical(hash_body))
    return result


def _write_json(path: Path, value: Any) -> bytes:
    raw = _canonical(value)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(raw)
    return raw


def _fixture(root: Path, *, with_provenance: bool = True, run_id: str = "run-a") -> tuple[Path, Path, str]:
    run = root / run_id
    spec = run / "run-spec"
    candidate = root / "staging"
    payload = candidate / "payload.bin"
    payload.parent.mkdir(parents=True, exist_ok=True)
    payload.write_bytes(b"generated bytes\n")
    candidate_digest, _ = cleanup._tree_digest(candidate)

    contract = _self_hashed(
        "cassi.qi-flow-contract-root.v1",
        {"contract_root_id": "fixture-root", "codec": "cassi.canonical-json.v1"},
        domain="cassi.qi-flow-contract-root-bootstrap.v1",
    )
    source = _self_hashed(
        "cassi.qi-flow-source-identity.v1",
        {"source_id": "fixture-source", "files": []},
        domain="cassi.qi-flow-source-identity.v1",
    )
    profile_body = {
        "profile_id": "fixture-profile",
        "contract_root_sha256": contract["self_sha256"],
        "execution": {"source_identity_sha256": source["self_sha256"]},
    }
    profile = _self_hashed("cassi.qi-flow-profile.v1", profile_body, field="profile_sha256", domain="cassi.qi-flow-profile.v1")
    retention = _self_hashed(
        "cassi.qi-flow-raw-retention-policy.v1",
        {"approved_digests": [candidate_digest], "retained_digests": [], "policy": "fixture"},
        domain="cassi.qi-flow-raw-retention-policy.v1",
    )
    dependency = _self_hashed(
        "cassi.qi-flow-dependency-manifest.v1",
        {"nodes": [], "edges": []},
        domain="cassi.qi-flow-dependency-manifest.v1",
    )
    controls: dict[str, dict[str, Any]] = {
        "manifest.json": _self_hashed(
            "cassi.qi-flow-manifest.v1",
            {"run_id": run_id, "phase": "fixture", "status": "PASS"},
        ),
        "profile.json": profile,
        "semantic-subhashes.json": _self_hashed("cassi.qi-flow-semantic-subhashes.v1", {"subhashes": []}, domain="cassi.qi-flow-semantic-subhashes.v1"),
        "profile-projections.json": _self_hashed("cassi.qi-flow-profile-projections.v1", {"projections": []}, domain="cassi.qi-flow-profile-projections.v1"),
        "schema-registry.json": _self_hashed("cassi.qi-flow-schema-registry.v1", {"schemas": []}, domain="cassi.qi-flow-schema-registry.v1"),
        "dependency-manifest.json": dependency,
        "contract-root.json": contract,
        "source-identity.json": source,
        "raw-retention-policy.json": retention,
        "capability-matrix.json": _self_hashed("cassi.qi-flow-capability-matrix.v1", {"capabilities": []}, domain="cassi.qi-flow-capability-matrix.v1"),
        "toolchain.json": _self_hashed("cassi.qi-flow-toolchain.v1", {"toolchain": "fixture"}, domain="cassi.qi-flow-toolchain.v1"),
        "command-inputs.json": _self_hashed("cassi.qi-flow-command-inputs.v1", {"commands": []}, domain="cassi.qi-flow-command-inputs.v1"),
        "static-fixture-index.json": _self_hashed(
            "cassi.qi-flow-static-fixture-index.v1",
            {
                "fixtures": ["run-spec/oracle-fixtures/contract-root-bootstrap.json"],
                "blocking_rule": "fixture is source-pinned W1 bootstrap input only",
            },
            domain="cassi.qi-flow-static-fixture-index.v1",
        ),
    }
    objects: list[dict[str, Any]] = []
    for name, value in controls.items():
        raw = _write_json(spec / name, value)
        objects.append({"path": f"run-spec/{name}", "sha256": _sha(raw), "byte_count": len(raw)})
    fixture_value = _self_hashed(
        "cassi.qi-flow-contract-root-bootstrap-fixture.v1",
        {"status": "PASS", "owner": "W0", "contract_root_sha256": contract["self_sha256"]},
        domain="cassi.qi-flow-contract-root-bootstrap-fixture.v1",
    )
    raw = _write_json(spec / "oracle-fixtures" / "contract-root-bootstrap.json", fixture_value)
    objects.append({"path": "run-spec/oracle-fixtures/contract-root-bootstrap.json", "sha256": _sha(raw), "byte_count": len(raw)})
    index_body = {
        "schema": "cassi.qi-flow-run-index.v1",
        "status": "PASS",
        "run_id": run_id,
        "object_count": len(objects),
        "objects": sorted(objects, key=lambda item: item["path"]),
    }
    _write_json(run / "index.json", _self_hashed("cassi.qi-flow-run-index.v1", {key: value for key, value in index_body.items() if key != "schema"}))
    if with_provenance:
        proof = _self_hashed(
            "cassi.qi-flow-artifact-provenance.v1",
            {
                "path": "staging",
                "sha256": candidate_digest,
                "generated": True,
                "sealed": False,
                "canonical": False,
                "dependency_closure": False,
            },
        )
        _write_json(candidate / ".provenance.json", proof)
    return run, candidate, candidate_digest


class ArtifactCleanupTests(unittest.TestCase):
    def test_canonical_retention_and_unproven_stage_are_report_only(self) -> None:

        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            run, candidate, _ = _fixture(root, with_provenance=False)
            before = (candidate / "payload.bin").read_bytes()
            report = cleanup.inventory_artifacts(root)
            self.assertEqual(report["status"], "BLOCKED")
            self.assertEqual(report["canonical_sealed_roots"][0]["status"], "canonical-sealed-retained")
            self.assertEqual(report["quarantine_candidates"], [])
            self.assertEqual(report["abandoned_staging_dirs"][0]["provenance_status"], "blocked")
            self.assertEqual((candidate / "payload.bin").read_bytes(), before)
            self.assertTrue((run / "index.json").is_file())
    def test_expected_self_hash_field_does_not_fallback(self) -> None:
        value = {"schema": "fixture", "self_sha256": _sha(_canonical({"schema": "fixture"}))}
        valid, _ = cleanup._verify_self_hash(value, field="profile_sha256")
        self.assertFalse(valid)

    def test_plan_is_digest_bound_and_quarantine_round_trip_moves_without_loss(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _, candidate, candidate_digest = _fixture(root)
            payload = candidate / "payload.bin"
            payload_before = payload.read_bytes()
            mtime_before = payload.stat().st_mtime_ns
            report = cleanup.inventory_artifacts(root)
            self.assertEqual(report["status"], "PASS")
            self.assertEqual([row["path"] for row in report["quarantine_candidates"]], ["staging"])
            plan = cleanup.build_cleanup_plan(report)
            self.assertEqual(plan["self_sha256"], _sha(_canonical({key: value for key, value in plan.items() if key != "self_sha256"})))
            self.assertEqual(payload.read_bytes(), payload_before)
            self.assertEqual(payload.stat().st_mtime_ns, mtime_before)
            receipt = cleanup.quarantine_artifacts(root, plan, expected_plan_sha256=plan["self_sha256"])
            destination = root / "quarantine" / candidate_digest
            self.assertFalse(candidate.exists())
            self.assertTrue(destination.is_dir())
            self.assertEqual((destination / "payload.bin").read_bytes(), payload_before)
            self.assertEqual(receipt["bytes_removed"], 0)
            self.assertEqual(receipt["moved"][0]["sha256"], candidate_digest)
            self.assertEqual(receipt["self_sha256"], _sha(_canonical({key: value for key, value in receipt.items() if key != "self_sha256"})))

    def test_tamper_or_wrong_plan_digest_rejects_before_moving(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _, candidate, _ = _fixture(root)
            plan = cleanup.build_cleanup_plan(cleanup.inventory_artifacts(root))
            (candidate / "payload.bin").write_bytes(b"tampered")
            with self.assertRaises(cleanup.ConcurrentChangeError):
                cleanup.quarantine_artifacts(root, plan, expected_plan_sha256=plan["self_sha256"])
            self.assertTrue(candidate.exists())

        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _fixture(root)
            plan = cleanup.build_cleanup_plan(cleanup.inventory_artifacts(root))
            with self.assertRaises(cleanup.CleanupError):
                cleanup.quarantine_artifacts(root, plan, expected_plan_sha256="0" * 64)
            self.assertTrue((root / "staging").exists())

    def test_duplicate_run_ids_reparse_and_cli_exact_report(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _fixture(root, run_id="run-a")
            _fixture(root, run_id="run-b")
            # Make the second sealed root claim the first root's identity.
            index = root / "run-b" / "index.json"
            value = json.loads(index.read_text(encoding="utf-8"))
            value["run_id"] = "run-a"
            value.pop("self_sha256", None)
            value["self_sha256"] = _sha(_canonical(value))
            index.write_bytes(_canonical(value))
            outside = root / "outside.bin"
            outside.write_bytes(b"outside")
            symlink = root / "undeclared-link"
            try:
                symlink.symlink_to(outside)
            except (OSError, NotImplementedError):
                symlink = None
            report = cleanup.inventory_artifacts(root)
            self.assertEqual(report["status"], "BLOCKED")
            self.assertTrue(report["duplicated_run_ids"])
            self.assertTrue(any(row["path"] == "outside.bin" for row in report["artifacts_outside_allowed_roots"]))
            if symlink is not None:
                self.assertTrue(report["undeclared_reparse_points"])

            completed = subprocess.run(
                [sys.executable, str(SCRIPT), "--mode", "report", "--root", str(root)],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(completed.returncode, 0, completed.stderr)
            cli_report = json.loads(completed.stdout)
            self.assertEqual(cli_report["schema"], cleanup.CLEANUP_SCHEMA)
            self.assertFalse(cli_report["release_ready"])
            self.assertFalse((root / "quarantine").exists())

    def test_cli_output_is_root_confined_and_never_overwritten(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _fixture(root)
            outside = root.parent / f"{root.name}-report.json"
            try:
                blocked = subprocess.run(
                    [
                        sys.executable,
                        str(SCRIPT),
                        "--mode",
                        "report",
                        "--root",
                        str(root),
                        "--out",
                        str(outside),
                    ],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(blocked.returncode, 2)
                self.assertFalse(outside.exists())

                existing = root / "report.json"
                existing.write_bytes(b"keep")
                blocked = subprocess.run(
                    [
                        sys.executable,
                        str(SCRIPT),
                        "--mode",
                        "report",
                        "--root",
                        str(root),
                        "--out",
                        "report.json",
                    ],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(blocked.returncode, 2)
                self.assertEqual(existing.read_bytes(), b"keep")
            finally:
                outside.unlink(missing_ok=True)

    def test_quarantine_destination_race_fails_closed_without_overwrite(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _, candidate, candidate_digest = _fixture(root)
            plan = cleanup.build_cleanup_plan(cleanup.inventory_artifacts(root))
            destination = root / "quarantine" / candidate_digest
            original = cleanup._rename_noreplace

            def race(source: Path, target: Path) -> None:
                target.mkdir()
                original(source, target)

            cleanup._rename_noreplace = race
            try:
                with self.assertRaises(cleanup.ConcurrentChangeError):
                    cleanup.quarantine_artifacts(root, plan, expected_plan_sha256=plan["self_sha256"])
                self.assertTrue(candidate.exists())
                self.assertTrue(destination.is_dir())
                self.assertEqual(list(destination.iterdir()), [])
            finally:
                cleanup._rename_noreplace = original
                destination.rmdir()

    def test_quarantine_reparse_root_fails_closed_before_move(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            _, candidate, _ = _fixture(root)
            plan = cleanup.build_cleanup_plan(cleanup.inventory_artifacts(root))
            escape = root.parent / f"{root.name}-escape"
            escape.mkdir()
            try:
                (root / "quarantine").symlink_to(escape, target_is_directory=True)
            except (OSError, NotImplementedError):
                escape.rmdir()
                self.skipTest("directory symlinks unavailable")
            try:
                with self.assertRaises(cleanup.CleanupError):
                    cleanup.quarantine_artifacts(root, plan, expected_plan_sha256=plan["self_sha256"])
                self.assertTrue(candidate.exists())
                self.assertEqual(list(escape.iterdir()), [])
            finally:
                (root / "quarantine").unlink(missing_ok=True)
                escape.rmdir()



if __name__ == "__main__":
    unittest.main()