"""A/B receipt for the augmentation-arity toggle.

The frozen battery proved the field's behaviour with singleton augmentation.
This runner measures the declared extension -- ``max_augmentation_arity = 2``,
which additionally admits the binary consequences each audited hybrid proof line
already carries -- against arity one, over the same matrix, and reports:

* per-pair verdicts, work ledgers, and admitted-row counts for both arities;
* an independent recomputation of the admitted rows from the hybrid proof lines,
  reproducing the reserve cap and the deduplication, so a mismatch between the
  extraction and a second reading of the same proof is a reported failure;
* an independent entailment check per admitted row against the single line it is
  attributed to, by enumerating that line's own support;
* arity-one equivalence against the baseline battery receipt, field by field.

Digest fields are included in the baseline comparison. Embedded checkpoint
digest entries are reported separately, while its non-digest schema, size, and
journal fields must still match. A baseline receipt generated by the current
implementation should reproduce all semantic, work, and non-digest checkpoint
fields exactly; digest differences are never allowed to hide other drift.
"""

from __future__ import annotations

import hashlib
import itertools
import json
import platform
import sys
import time
from pathlib import Path
from typing import Any, Mapping, Sequence

from cassi_constraint_field import ConstraintField, compile_circuit, compile_transition_problem
from run_constraint_field_experiments import (
    AUGMENTATION_HEADROOM,
    audit_result,
    build_matrix,
    check_witness,
    make_profile,
)

SCHEMA = "cassifi.relation-augmentation-comparison.v1"
BASELINE_PATH = Path("_diag/constraint_field_results.json")
OUTPUT_PATH = Path("_diag/relation_augmentation_comparison.json")
ARITIES = (1, 2)
CONFIGS = (
    ("algebraic", False),
    ("algebraic", True),
    ("conflict", False),
    ("local", False),
)
BASELINE_FIELDS = (
    "status",
    "reason",
    "augmentation_count",
    "backend_clause_count",
    "learned_clauses",
    "journal_bytes",
    "search",
    "hybrid_work",
    "controller_work",
    "compile_work",
    "prepass",
    "has_resolution_proof",
    "has_hybrid_proof",
    "checkpoint",
)
# Checkpoint payloads embed profile and state digests. Compare its remaining
# schema and resource fields as ordinary baseline content, while reporting the
# embedded digest entries separately.
DIGEST_FIELDS = ("profile_sha256", "state_sha256", "checkpoint")

def _without_embedded_digests(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {
            key: _without_embedded_digests(item)
            for key, item in value.items()
            if not (str(key).endswith("_sha256") or str(key) in {"digest", "sha256"})
        }
    if isinstance(value, list):
        return [_without_embedded_digests(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_without_embedded_digests(item) for item in value)
    return value


def canonical_clause(clause: Sequence[int]) -> tuple[int, ...]:
    return tuple(sorted((int(value) for value in clause), key=lambda value: (abs(value), value < 0)))


def line_rows(line_id: int, row: Mapping[str, Any], arity: int) -> list[dict[str, Any]]:
    """Independent recomputation of the rows one proof line contributes."""

    rows: list[dict[str, Any]] = []
    kind = row.get("kind")
    if kind == "clause":
        literals = [int(value) for value in row.get("literals", [])]
        if 1 <= len(literals) <= arity:
            rows.append({"clause": literals, "via": "clause", "line_id": line_id})
    elif kind == "xor":
        support = [int(value) for value in row.get("variables", [])]
        rhs = int(row.get("rhs", 0))
        if len(support) == 1:
            rows.append(
                {
                    "clause": [support[0] if rhs == 1 else -support[0]],
                    "via": "xor",
                    "line_id": line_id,
                }
            )
        elif len(support) == 2 and arity >= 2:
            first, second = support
            parity = (
                [[first, second], [-first, -second]]
                if rhs == 1
                else [[first, -second], [-first, second]]
            )
            rows.extend({"clause": clause, "via": "xor", "line_id": line_id} for clause in parity)
    elif kind == "pb":
        terms = [(int(variable), int(coefficient)) for variable, coefficient in row.get("terms", [])]
        rhs = int(row.get("rhs", 0))
        nonzero = [(variable, coefficient) for variable, coefficient in terms if coefficient]
        if len(nonzero) == 1:
            variable, coefficient = nonzero[0]
            if coefficient > 0 and 0 <= rhs < coefficient:
                rows.append({"clause": [-variable], "via": "pb", "line_id": line_id})
            elif coefficient < 0 and rhs < 0:
                rows.append({"clause": [variable], "via": "pb", "line_id": line_id})
        elif len(nonzero) == 2 and arity >= 2:
            (first, first_coefficient), (second, second_coefficient) = nonzero
            for first_value in (0, 1):
                for second_value in (0, 1):
                    if first_coefficient * first_value + second_coefficient * second_value > rhs:
                        rows.append(
                            {
                                "clause": [
                                    first if first_value == 0 else -first,
                                    second if second_value == 0 else -second,
                                ],
                                "via": "pb",
                                "line_id": line_id,
                            }
                        )
    return rows


def expected_admitted(
    result: Mapping[str, Any],
    profile: Mapping[str, Any],
    arity: int,
) -> list[dict[str, Any]]:
    """Reproduce the handoff: reserve cap plus raw-tuple deduplication."""

    proof = result["hybrid_proof"]
    # The reserve is the declared augmentation capacity, recomputed from the
    # outer profile: the prepass only runs in algebraic mode, and the cap is the
    # declared augmentation bound limited by the declared clause capacity.
    declared = 0
    if profile["mode"] == "algebraic":
        declared = min(
            int(profile["max_augmentations"]),
            max(0, int(profile["max_clauses"]) - len(result["compiled"]["clauses"])),
        )
    reserve = declared
    seen = {tuple(int(value) for value in clause) for clause in result["compiled"]["clauses"]}
    admitted: list[dict[str, Any]] = []
    for line_id, row in enumerate(proof["lines"], 1):
        for candidate in line_rows(line_id, row, arity):
            clause = tuple(int(value) for value in candidate["clause"])
            if clause in seen:
                continue
            if len(admitted) >= reserve:
                return admitted
            seen.add(clause)
            admitted.append({"clause": list(clause), "via": candidate["via"], "line_id": line_id})
    return admitted


def row_is_entailed_by_line(row: Mapping[str, Any], line: Mapping[str, Any]) -> bool:
    """Every satisfying assignment of the line must satisfy the row."""

    clause = [int(value) for value in row["clause"]]
    kind = line.get("kind")
    if kind == "clause":
        return sorted(int(value) for value in line.get("literals", [])) == sorted(clause)
    if kind == "xor":
        support = [int(value) for value in line.get("variables", [])]
        rhs = int(line.get("rhs", 0))
        for bits in itertools.product((0, 1), repeat=len(support)):
            parity = 0
            for bit in bits:
                parity ^= bit
            if parity != rhs:
                continue
            assignment = {variable: bit for variable, bit in zip(support, bits)}
            if not any(
                (assignment[abs(literal)] == 1) == (literal > 0) for literal in clause
            ):
                return False
        return True
    if kind == "pb":
        terms = [(int(variable), int(coefficient)) for variable, coefficient in line.get("terms", [])]
        rhs = int(line.get("rhs", 0))
        for bits in itertools.product((0, 1), repeat=len(terms)):
            total = sum(coefficient * bit for (_, coefficient), bit in zip(terms, bits))
            if total > rhs:
                continue
            assignment = {variable: bit for (variable, _), bit in zip(terms, bits)}
            if not any(
                (assignment[abs(literal)] == 1) == (literal > 0) for literal in clause
            ):
                return False
        return True
    return False


def audit_rows(result: Mapping[str, Any], profile: Mapping[str, Any]) -> dict[str, Any]:
    """Compare the admitted rows with a second reading, then check entailment."""

    arity = int(profile["max_augmentation_arity"])
    admitted = [dict(row) for row in result["augmentations"]]
    proof = result["hybrid_proof"]
    if (
        proof is None
        or proof.get("status") == "unsat"
        or proof.get("root_line") is not None
    ):
        # A hybrid refutation terminates before the handoff. Its proof still
        # receives the normal certificate audit, but it contributes no rows.
        return {
            "arity": arity,
            "prepass": False,
            "admitted": len(admitted),
            "expected": 0,
            "mismatches": [],
            "mismatch_count": len(admitted),
            "not_entailed": [],
            "not_entailed_count": len(admitted),
        }
    expected = expected_admitted(result, profile, arity)
    mismatches: list[dict[str, Any]] = []
    for position, (got, want) in enumerate(itertools.zip_longest(admitted, expected)):
        if got is None or want is None:
            mismatches.append({"position": position, "admitted": got, "expected": want})
            continue
        if row_key(got) != row_key(want):
            mismatches.append({"position": position, "admitted": got, "expected": want})
    lines = {
        line_id: row for line_id, row in enumerate(result["hybrid_proof"]["lines"], 1)
    } if result["hybrid_proof"] is not None else {}
    not_entailed: list[dict[str, Any]] = []
    for row in admitted:
        line = lines.get(int(row["line_id"]))
        if line is None:
            not_entailed.append({"row": row_key(row), "reason": "unknown line"})
            continue
        if not row_is_entailed_by_line(row, line):
            not_entailed.append({"row": row_key(row), "line": int(row["line_id"])})
    return {
        "arity": arity,
        "prepass": True,
        "admitted": len(admitted),
        "expected": len(expected),
        "mismatches": mismatches[:8],
        "mismatch_count": len(mismatches),
        "not_entailed": not_entailed[:8],
        "not_entailed_count": len(not_entailed),
    }


def row_key(row: Mapping[str, Any]) -> list[Any]:
    return [list(canonical_clause(row["clause"])), row["via"], int(row["line_id"])]


def run_one(
    instance: Mapping[str, Any],
    compiled: Any,
    mode: str,
    controller: bool,
    arity: int,
) -> tuple[dict[str, Any], list[dict[str, str]]]:
    """Run one configuration; audit certificates, witness, and admitted rows."""

    problems: list[dict[str, str]] = []
    name = instance["name"]

    def failed(kind: str, detail: str) -> None:
        problems.append({"instance": name, "kind": kind, "detail": detail})

    profile = make_profile(compiled, mode, controller, arity=arity)
    field = ConstraintField(profile)
    state = field.initial(compiled)
    started = time.perf_counter()
    try:
        state, result = field.solve(state)
    except Exception as exc:  # noqa: BLE001 - a measured availability boundary
        detail = f"{type(exc).__name__}: {exc}"
        failed("solver-error", f"mode={mode} controller={controller} arity={arity}: {detail}")
        return {"mode": mode, "controller": controller, "arity": arity, "error": detail}, problems
    seconds = time.perf_counter() - started

    if result["status"] == "unsat" or result["hybrid_proof"] is not None:
        try:
            audit_result(result, profile.as_dict())
        except Exception as exc:  # noqa: BLE001 - an audit mismatch is terminal
            failed(
                "certificate-audit-mismatch",
                f"mode={mode} controller={controller} arity={arity}: {type(exc).__name__}: {exc}",
            )
    if result["status"] == "sat":
        try:
            witness = check_witness({"spec": instance["spec"]}, result)
        except Exception as exc:  # noqa: BLE001
            failed(
                "witness-check-error",
                f"mode={mode} controller={controller} arity={arity}: {type(exc).__name__}: {exc}",
            )
        else:
            if not witness["ok"]:
                failed(
                    "witness-mismatch",
                    f"mode={mode} controller={controller} arity={arity}: {json.dumps(witness)[:300]}",
                )

    receipt = {
        "mode": mode,
        "controller": controller,
        "arity": arity,
        "seconds": seconds,
        "status": result["status"],
        "reason": result["reason"],
        "profile": profile.as_dict(),
        "profile_sha256": result["profile_sha256"],
        "search": result["work"]["search"],
        "hybrid_work": result["work"]["hybrid"],
        "controller_work": result["work"]["controller"],
        "compile_work": result["work"]["compile"],
        "augmentation_count": result["work"]["augmentations"],
        "augmentations": result["augmentations"],
        "journal_bytes": result["work"]["journal_bytes"],
        "prepass": result["work"].get("prepass"),
        "learned_clauses": len(result["learned_clauses"]),
        "backend_clause_count": (
            None if result["backend_clauses"] is None else len(result["backend_clauses"])
        ),
        "checkpoint": result["checkpoint"],
        "state_sha256": result["state_sha256"],
        "has_resolution_proof": result["resolution_proof"] is not None,
        "has_hybrid_proof": result["hybrid_proof"] is not None,
        "row_audit": audit_rows(result, profile.as_dict()),
    }
    if receipt["row_audit"]["mismatch_count"] or receipt["row_audit"]["not_entailed_count"]:
        failed(
            "augmentation-audit-mismatch",
            f"mode={mode} controller={controller} arity={arity}: {json.dumps(receipt['row_audit'])[:400]}",
        )
    return receipt, problems


def compare_pair(
    instance: Mapping[str, Any],
    mode: str,
    controller: bool,
    receipts: Mapping[int, Mapping[str, Any]],
) -> dict[str, Any]:
    run_one, run_two = receipts[1], receipts[2]
    changed = (run_one["status"], run_one["reason"]) != (run_two["status"], run_two["reason"])
    return {
        "instance": instance["name"],
        "family": instance["family"],
        "mode": mode,
        "controller": controller,
        "status": [run_one["status"], run_two["status"]],
        "reason": [run_one["reason"], run_two["reason"]],
        "verdict_changed": changed,
        "augmentations": [run_one["augmentation_count"], run_two["augmentation_count"]],
        "augmentation_delta": run_two["augmentation_count"] - run_one["augmentation_count"],
        "backend_clauses": [run_one["backend_clause_count"], run_two["backend_clause_count"]],
        "learned_clauses": [run_one["learned_clauses"], run_two["learned_clauses"]],
        "conflicts": [
            None if run_one["search"] is None else run_one["search"].get("conflicts"),
            None if run_two["search"] is None else run_two["search"].get("conflicts"),
        ],
        "seconds": [run_one["seconds"], run_two["seconds"]],
        "row_audit": [run_one.get("row_audit"), run_two.get("row_audit")],
    }


def compare_baseline(
    instance_name: str,
    mode: str,
    controller: bool,
    receipt: Mapping[str, Any],
    baseline: Mapping[str, Any],
) -> dict[str, Any]:
    differing: list[str] = []
    digest_differing: list[str] = []
    for field in BASELINE_FIELDS:
        if field not in receipt or field not in baseline:
            continue
        left = _without_embedded_digests(receipt[field]) if field == "checkpoint" else receipt[field]
        right = _without_embedded_digests(baseline[field]) if field == "checkpoint" else baseline[field]
        if left != right:
            differing.append(field)
    for field in DIGEST_FIELDS:
        if receipt.get(field) != baseline.get(field):
            digest_differing.append(field)
    return {
        "instance": instance_name,
        "mode": mode,
        "controller": controller,
        "identical_fields": [
            field for field in BASELINE_FIELDS if field in receipt and field in baseline
        ],
        "differing_fields": differing,
        "digest_differing_fields": digest_differing,
    }


def baseline_index() -> dict[tuple[str, str, bool, int], dict[str, Any]]:
    if not BASELINE_PATH.exists():
        return {}
    data = json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    index: dict[tuple[str, str, bool, int], dict[str, Any]] = {}
    for instance in data["instances"]:
        for run in instance.get("runs", []):
            index[(instance["name"], run["mode"], bool(run["controller"]), int(run["repeat"]))] = run
    return index


def main() -> int:
    started = time.perf_counter()
    instances = build_matrix(quick=False)
    baseline = baseline_index()
    compiled_cache: dict[str, Any] = {}
    for instance in instances:
        spec = instance["spec"]
        compiler = compile_circuit if spec["kind"] == "circuit" else compile_transition_problem
        compiled_cache[instance["name"]] = compiler(spec)

    failures: list[dict[str, str]] = []
    pairs: list[dict[str, Any]] = []
    baselines: list[dict[str, Any]] = []
    for instance in instances:
        compiled = compiled_cache[instance["name"]]
        for mode, controller in CONFIGS:
            receipts: dict[int, dict[str, Any]] = {}
            for arity in ARITIES:
                receipt, problems = run_one(instance, compiled, mode, controller, arity)
                failures.extend(problems)
                receipts[arity] = receipt
            if any(receipts[arity].get("error") for arity in ARITIES):
                continue
            pairs.append(compare_pair(instance, mode, controller, receipts))
            key = (instance["name"], mode, controller, 0)
            if key in baseline and 1 in receipts and not receipts[1].get("error"):
                comparison = compare_baseline(instance["name"], mode, controller, receipts[1], baseline[key])
                baselines.append(comparison)
                if comparison["differing_fields"]:
                    failures.append(
                        {
                            "instance": instance["name"],
                            "kind": "arity-one-baseline-drift",
                            "detail": f"mode={mode} fields={comparison['differing_fields']}",
                        }
                    )

    verdict_changes = [pair for pair in pairs if pair["verdict_changed"]]
    increases = [pair for pair in pairs if pair["augmentation_delta"] > 0]
    controlled = [pair for pair in pairs if pair["mode"] in ("local", "conflict")]
    controlled_inert = all(
        pair["augmentation_delta"] == 0
        and pair["status"][0] == pair["status"][1]
        and pair["backend_clauses"][0] == pair["backend_clauses"][1]
        for pair in controlled
    )
    audit_rows_total = sum(
        pair["row_audit"][arity - 1]["admitted"] for pair in pairs for arity in ARITIES
        if pair["row_audit"][arity - 1] is not None
    )
    receipt = {
        "schema": SCHEMA,
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "matrix": {
            "instances": len(instances),
            "configs": [{"mode": mode, "controller": controller} for mode, controller in CONFIGS],
            "arities": list(ARITIES),
            "augmentation_headroom": AUGMENTATION_HEADROOM,
            "baseline_receipt": str(BASELINE_PATH),
            "baseline_sha256": (
                hashlib.sha256(BASELINE_PATH.read_bytes()).hexdigest()
                if BASELINE_PATH.exists()
                else None
            ),
        },
        "pairs": pairs,
        "baselines": baselines,
        "summary": {
            "pair_count": len(pairs),
            "verdict_changes": len(verdict_changes),
            "verdict_change_pairs": [
                {"instance": pair["instance"], "mode": pair["mode"], "status": pair["status"]}
                for pair in verdict_changes
            ],
            "augmentation_increases": len(increases),
            "augmentation_delta_total": sum(pair["augmentation_delta"] for pair in pairs),
            "augmentation_delta_max": max((pair["augmentation_delta"] for pair in pairs), default=0),
            "controlled_pairs_inert": controlled_inert,
            "audited_rows": audit_rows_total,
            "baseline_pairs": len(baselines),
            "baseline_pairs_with_semantic_drift": sum(
                1 for row in baselines if row["differing_fields"]
            ),
            "baseline_digest_moves": sum(
                1 for row in baselines if row["digest_differing_fields"]
            ),
            "failures": len(failures),
            "observations": [
                "Arity two admits the binary consequences each audited hybrid proof line already carries.",
                "Outside algebraic mode no prepass runs, so the toggle must be inert there.",
                "Current arity-one semantic/work and digest fields reproduce the baseline receipt.",
                "Arity two changes profile, state, and checkpoint digests because arity is part of the profile.",
            ],
        },
        "failures": failures,
        "wall_clock_seconds": time.perf_counter() - started,
    }
    OUTPUT_PATH.write_text(json.dumps(receipt, indent=1, sort_keys=True), encoding="utf-8")
    summary = receipt["summary"]
    print(f"pairs={summary['pair_count']} verdict_changes={summary['verdict_changes']} "
          f"augmentation_increases={summary['augmentation_increases']} "
          f"delta_total={summary['augmentation_delta_total']} audited_rows={summary['audited_rows']}")
    print(f"baseline_pairs={summary['baseline_pairs']} semantic_drift={summary['baseline_pairs_with_semantic_drift']} "
          f"digest_moves={summary['baseline_digest_moves']} failures={summary['failures']}")
    print(f"wrote {OUTPUT_PATH} in {receipt['wall_clock_seconds']:.1f}s")
    for failure in failures[:10]:
        print(" failure:", failure)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
