#!/usr/bin/env python3
"""Lattice-stack probe, wave 2: critical height (A), two-level stack-of-stacks (B), controls (C).

Run:  python two-fluid/run_lattice_stack2_probe.py
      (--steps N, --arm TAG repeatable, --init-check build-only overrides)

Extends the committed run_lattice_stack_probe machinery (imported read-only)
to two new constructions; same protocol: fresh solver per arm, N = 48,
gate 'five', dt = 0.001, t = 40 = 2/lambda, canonical solver untouched,
zero new terms, no registry changes.

Arms A (critical height at the small decagon step dtheta = pi/5):
  a8_pi5   M = 8   (published geometry; rerun for a same-family record)
  a16_pi5  M = 16  (3-cell spacing)
  a32_pi5  M = 32  (1.5-cell spacing -- seam/overlap reliability boundary
                    reported; verdicts keep M = 16 if it is unreliable)
  Verdict B2: M* = smallest M in {8, 16, 32} with the two-hump envelope
  persisting to t = 40 (C_abs(40) >= 0.5).

Arms B (two-level stack-of-stacks): R rungs, each a stack of M = 4 layers
at intra-rung dtheta_1 = 2 pi/5; rung r carries phase r*dtheta_2 on top of
the layer phases:  theta(r, i) = r*dtheta_2 + i*dtheta_1,  layers on the
uniform lattice of period 48/(R*M), rung-major order.  R in {2, 4},
dtheta_2 in {0, 2 pi/5, pi/5, pi} (8 arms).  The total phasor sum factors:
  A_tot = s_tot * |sum_r e^{i r dtheta_2}| * |sum_i e^{i i dtheta_1}|
        = s_tot * A1(R, dtheta_2) * A2(M, dtheta_1),   A2(4, 2pi/5) = 1.
  Verdict B3: factorization at t = 0 within float tolerance.
  Verdict B4: inter-rung persistence ranking (which dtheta_2 holds the
  envelope to t = 40).
  Verdict B5 (P_parallel = 2 clash): dtheta_2 = pi arms -- adjacent rungs
  anti-phase; does the full envelope cancel exactly at t = 0 (A1 = 0) and
  is the transverse profile flat (C_abs ~ 0), like the m8_pi arm?

Arms C (controls):
  c1_0    M = 1 baseline rerun (B1: continuity with the published record)
  c1_r1   R = 1 two-level arm = the published m4_2pi5 (B1 continuity and
          the R = 1 endpoint of the factorization check)

Telemetry per arm: mass drift, init floor cells, run-min fields, NaNs.

Output: runs/<rid>_lattice_stack2/run_<arm>.json + results.json (raw;
NO doc changes, NO commit -- director reads the raw outputs first).
"""

import os
import sys
import json
import time
import math
import argparse
from datetime import datetime

import numpy as np
import torch

torch.backends.cudnn.benchmark = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import run_trauma_wake_lock as T
import run_two_strand_probe as P
import run_lattice_stack_probe as L1

T.LAM = 0.05
T.DT = 0.001
T.REPORT = 50
STEPS = 40000                 # t = 40 = 2/lambda

SIG, SEP, E_RIDGE, BETA, RHO0 = L1.SIG, L1.SEP, L1.E_RIDGE, L1.BETA, L1.RHO0

DTH1 = 2.0 * np.pi / 5.0      # intra-rung step (pentagon)
DTH_A = np.pi / 5.0           # arms A step (decagon)


def stack_init_phases(solver, phases):
    """Layers on the uniform lattice (period N/len(phases) along z), each
    with its own phase: the same (rho, eps) doublet rotation as the
    committed stack_init, generalized to an arbitrary per-layer phase list.
    Rung-major two-level phases are generated by the caller.  Bit-identical
    to run_lattice_stack_probe.stack_init for phases = [i*dtheta]."""
    N_ = solver.N
    dev = solver.device
    M = len(phases)
    x = torch.arange(N_, dtype=torch.float64, device=dev)
    X, Y, Z = torch.meshgrid(x, x, x, indexing='ij')
    cx = N_ / 2.0
    c1, c2 = cx - SEP / 2.0, cx + SEP / 2.0
    spacing = N_ / M
    zs = [cx + (j - (M - 1) / 2.0) * spacing for j in range(M)]
    rho = torch.full((N_, N_, N_), RHO0, dtype=torch.float64, device=dev)
    eps = torch.zeros_like(rho)
    offsets = (0.0, float(N_), -float(N_))
    for j, (zi, ph) in enumerate(zip(zs, phases)):
        ct, st = math.cos(ph), math.sin(ph)
        g1 = torch.zeros_like(X)
        g2 = torch.zeros_like(X)
        for off in offsets:
            zc = Z - zi + off
            g1 = g1 + torch.exp(-((X - c1) ** 2 + (Y - cx) ** 2 + zc ** 2)
                                / (2.0 * SIG ** 2))
            g2 = g2 + torch.exp(-((X - c2) ** 2 + (Y - cx) ** 2 + zc ** 2)
                                / (2.0 * SIG ** 2))
        gp = g1 + g2
        gm = g1 - g2
        rho += RHO0 * BETA * gp * ct - E_RIDGE * gm * st
        eps += RHO0 * BETA * gp * st + E_RIDGE * gm * ct
    ey = (T.PHI * rho + eps) / (1.0 + T.PHI)
    ei = (rho - eps) / (1.0 + T.PHI)
    ey = torch.clamp(ey, min=1e-3)
    ei = torch.clamp(ei, min=1e-3)
    u_hat = torch.zeros(3, N_, N_, N_, dtype=torch.complex128, device=dev)
    return torch.fft.fftn(ey), torch.fft.fftn(ei), u_hat, zs


def measure2(solver, ey, ei, rho_prof, centers, prev, windows, zs, rho_bg,
             rung_of=None):
    """L1.measure plus per-rung circular-mean phases and the inter-rung ramp."""
    d = L1.measure(solver, ey, ei, rho_prof, centers, prev, windows, zs, rho_bg)
    if rung_of is not None:
        lp = np.array(d['layer_phase'])
        n_rungs = int(max(rung_of)) + 1
        rung_ph = [float(np.angle(np.sum(np.exp(1j * lp[rung_of == r]))))
                   for r in range(n_rungs)]
        d['rung_phase'] = rung_ph
        if n_rungs > 1:
            steps = []
            for r in range(n_rungs - 1):
                dv = (rung_ph[r + 1] - rung_ph[r]) % (2.0 * np.pi)
                if dv > np.pi:
                    dv -= 2.0 * np.pi
                steps.append(dv)
            d['rung_ramp'] = steps
    return d


def resonance_t0(solver, ey, ei, windows, zs, phases, A1, A2):
    """t=0 resonance/factorization record (construction background RHO0)."""
    S = L1.slab_phasor(ey, ei, RHO0)
    A_tot = float(S.sum().abs())
    s_tot = 2.0 * RHO0 * BETA * (2.0 * np.pi) ** 1.5 * SIG ** 3
    W = (windows.to(torch.complex128) @ S).cpu().numpy()
    ph = np.angle(W)
    adv = []
    for i in range(len(zs) - 1):
        dv = (ph[i + 1] - ph[i]) % (2.0 * np.pi)
        if dv > np.pi:
            dv -= 2.0 * np.pi
        adv.append(dv)
    return {
        'A_tot': A_tot,
        's_tot_analytic': s_tot,
        'ratio_vs_analytic': A_tot / max(s_tot, 1e-30),
        'A1': A1, 'A2': A2,
        'A_tot_pred': s_tot * A1 * A2,
        'factor_ratio': A_tot / max(s_tot * A1 * A2, 1e-30) if A1 > 1e-9
                        else A_tot / max(s_tot, 1e-30),
        'layer_phase': ph.tolist(),
        'layer_amp': np.abs(W).tolist(),
        'phase_advance': adv,
        'max_advance_dev': max((abs(a - (phases[i + 1] - phases[i])
                                     if i < len(phases) - 1 else 0.0)
                                for i, a in enumerate(adv)), default=0.0),
        'floor_ey': int((ey <= 1e-3 + 1e-12).sum()),
        'floor_ei': int((ei <= 1e-3 + 1e-12).sum()),
        'min_ey': float(ey.min()),
        'min_ei': float(ei.min()),
    }


def run_case2(solver, tag, phases, rung_of, outdir, steps=STEPS):
    M = len(phases)
    print(f"\n=== run: {tag} (layers={M}, rungs="
          f"{max(rung_of) + 1 if rung_of else 1}) ===")
    ey_hat, ei_hat, u_hat, zs = stack_init_phases(solver, phases)
    centers = [solver.N / 2.0 - SEP / 2.0, solver.N / 2.0 + SEP / 2.0]
    windows = L1.layer_windows(solver.N, zs, solver.device)
    ey0 = torch.fft.ifftn(ey_hat).real
    ei0 = torch.fft.ifftn(ei_hat).real
    res0 = resonance_t0(solver, ey0, ei0, windows, zs, phases, 0.0, 0.0)
    res0['min_ey'] = float(ey0.min())
    res0['min_ei'] = float(ei0.min())
    print(f"  t=0: A_tot={res0['A_tot']:.4f} (s_tot={res0['s_tot_analytic']:.2f}, "
          f"ratio={res0['ratio_vs_analytic']:.5f}) | "
          f"min fields {res0['min_ey']:.4f}/{res0['min_ei']:.4f} | "
          f"floor cells {res0['floor_ey']}/{res0['floor_ei']}")

    t0 = time.time()
    hist = []
    prev = None
    profiles = {}
    S0 = L1.slab_phasor(ey0, ei0, RHO0).cpu().numpy()
    J0, F0, _, _ = L1.current_profiles(solver, ey0, ei0, zs)
    profiles['0.0'] = {'A': np.abs(S0).tolist(), 'arg': np.angle(S0).tolist(),
                       'Jz': J0.tolist(), 'Fc': F0.tolist()}
    for step in range(steps):
        u_hat, ey_hat, ei_hat = solver.rk2_step(u_hat, ey_hat, ei_hat, T.DT)
        if step % T.REPORT == 0 or step == steps - 1:
            ey = torch.fft.ifftn(ey_hat).real
            ei = torch.fft.ifftn(ei_hat).real
            rho_prof = (ey + ei).sum(dim=(1, 2)).cpu().numpy()
            rho_bg = RHO0 if step == 0 else float((ey + ei).mean())
            d = measure2(solver, ey, ei, rho_prof, centers, prev,
                         windows, zs, rho_bg, rung_of)
            prev = ([d['x1'], d['x2']] if not d['merged'] else [d['x1']])
            d.update({'step': step, 't': step * T.DT})
            hist.append(d)
            if abs(step * T.DT - 4.0) < 0.6 or abs(step * T.DT - 40.0) < 0.6 \
                    or step == steps - 1:
                rho_m = float((ey + ei).mean())
                Sn = L1.slab_phasor(ey, ei, rho_m).cpu().numpy()
                Jn, Fn, _, _ = L1.current_profiles(solver, ey, ei, zs)
                profiles[f"{step * T.DT:.1f}"] = {
                    'A': np.abs(Sn).tolist(), 'arg': np.angle(Sn).tolist(),
                    'Jz': Jn.tolist(), 'Fc': Fn.tolist()}
            if step % 1000 == 0 or step == steps - 1:
                print(f"  t={step*T.DT:6.2f} | d={d['d']:6.3f} "
                      f"Rc={d['Rc']:6.2f} | A_peak={d['A_peak']:7.2f} "
                      f"C_abs={d['C_abs']:+.3f} wind={d['winding']:+6.3f} "
                      f"|Jz|={d['Jz_abs_mean']:8.1f} | q_mid={d['q_mid']:.4f} "
                      f"q_flank={d['q_flank']:.4f} | "
                      f"ey_min={d['ey_min']:.4f} ei_min={d['ei_min']:.4f}")
    elapsed = time.time() - t0
    print(f"  [{tag}] {steps} steps in {elapsed:.1f}s")
    if outdir:
        with open(f"{outdir}/run_{tag}.json", "w") as f:
            json.dump({'kind': tag, 'phases': phases,
                       'rung_of': rung_of,
                       'n_layers': M,
                       'n_rungs': max(rung_of) + 1 if rung_of else 1,
                       'zs': zs, 'steps': steps,
                       'resonance_t0': res0, 'profiles': profiles,
                       'hist': hist}, f, indent=1)
    return {'tag': tag, 'phases': phases, 'rung_of': rung_of,
            'n_layers': M, 'n_rungs': max(rung_of) + 1 if rung_of else 1,
            'elapsed': elapsed, 'resonance_t0': res0, 'hist': hist,
            'profiles': profiles}


def at_t(hist, t_target):
    return min(hist, key=lambda d: abs(d['t'] - t_target))


def summarize2(r):
    h = r['hist']
    t0, t4, t40 = h[0], at_t(h, 4.0), at_t(h, 40.0)
    return {
        't0': {'A_peak': t0['A_peak'], 'C_abs': t0['C_abs'],
               'winding': t0['winding'], 'Jz': t0['Jz_abs_mean'],
               'd': t0['d']},
        't4': {'d': t4['d'], 'C_abs': t4['C_abs'], 'A_peak': t4['A_peak'],
               'winding': t4['winding'], 'delta_theta': t4['delta_theta'],
               'q_mid': t4['q_mid']},
        't40': {'d': t40['d'], 'C_abs': t40['C_abs'], 'A_peak': t40['A_peak'],
                'winding': t40['winding'], 'delta_theta': t40['delta_theta'],
                'A_plus': t40['A_plus'], 'q_mid': t40['q_mid'],
                'merged': t40['merged']},
        'A_peak_ratio_t4': t4['A_peak'] / max(t0['A_peak'], 1e-30),
        'A_peak_ratio_t40': t40['A_peak'] / max(t0['A_peak'], 1e-30),
        'mass_drift': abs(t40['mass'] - t0['mass']) / max(t0['mass'], 1e-30),
        'ey_min': min(d['ey_min'] for d in h),
        'ei_min': min(d['ei_min'] for d in h),
        'nan': any(np.isnan(d['A_peak']) for d in h),
    }


def build_arms():
    """(tag, phases, rung_of) for the full matrix."""
    arms = []
    # C: controls
    arms.append(('c1_0', [0.0], None))
    arms.append(('c1_r1', [i * DTH1 for i in range(4)], [0] * 4))
    # A: critical height at pi/5
    for M in (8, 16, 32):
        arms.append((f'a{M}_pi5', [i * DTH_A for i in range(M)], None))
    # B: two-level stack-of-stacks
    for R in (2, 4):
        for dth2 in (0.0, 2.0 * np.pi / 5.0, np.pi / 5.0, np.pi):
            phases = []
            rung_of = []
            for r in range(R):
                for i in range(4):
                    phases.append(r * dth2 + i * DTH1)
                    rung_of.append(r)
            tag = f'b{R}_' + {0.0: '0', 2.0 * np.pi / 5.0: '2pi5',
                              np.pi / 5.0: 'pi5', np.pi: 'pi'}[dth2]
            arms.append((tag, phases, rung_of))
    return arms


def A1_factor(R, dth2):
    """|sum_{r=0}^{R-1} e^{i r dth2}| (the inter-rung array factor)."""
    if abs(dth2) < 1e-12:
        return float(R)
    if abs(math.sin(dth2 / 2.0)) < 1e-12:
        return 0.0
    return abs(math.sin(R * dth2 / 2.0) / math.sin(dth2 / 2.0))


def finalize(runs, rdir):
    for r in runs:
        r['summary'] = summarize2(r)
    s_tot = float(2.0 * RHO0 * BETA * (2.0 * np.pi) ** 1.5 * SIG ** 3)

    def arm(tag):
        return next((r for r in runs if r['tag'] == tag), None)

    results = {
        'meta': {'N': T.N, 'lam': T.LAM, 'dt': T.DT,
                 't_end': runs[0]['hist'][-1]['t'],
                 'gate_model': 'five (solver)',
                 'wave': 'lattice-stack 2: critical height + stack-of-stacks',
                 'intra_rung_step': DTH1, 'arms_A_step': DTH_A,
                 'protocol': 'fresh solver per arm, t=40=2/lambda, '
                             'init-only phases, canonical solver untouched'},
        'arms': {},
    }
    for r in runs:
        R = r['n_rungs']
        dth2 = r['phases'][4] - r['phases'][0] if R and len(r['phases']) > 4 \
            else 0.0
        info = {'n_layers': r['n_layers'], 'n_rungs': R,
                'resonance_t0': r['resonance_t0'], 'summary': r['summary'],
                'elapsed_s': r['elapsed']}
        if R and r['tag'] not in ('c1_0',) and len(r['phases']) > 4:
            info['A1'] = A1_factor(R, dth2)
            info['A2'] = 1.0
            info['dtheta2'] = dth2
        results['arms'][r['tag']] = info

    print(f"\n=== LATTICE-STACK-2 RESULTS (t=40) ===")
    # B1: baseline continuity
    c1 = arm('c1_0')
    if c1 is not None:
        c1 = c1['summary']
        b1_ok = (9.85 <= c1['t4']['d'] <= 10.5 and 14.5 <= c1['t40']['d'] <= 17.0
                 and c1['t40']['delta_theta'] <= 0.10 and c1['t40']['A_plus'] <= 0.20
                 and 0.705 <= c1['t40']['q_mid'] <= 0.712)
        print(f"B1 baseline continuity: c1_0 d 9.90->{c1['t4']['d']:.2f}->"
              f"{c1['t40']['d']:.2f} dth(40)={c1['t40']['delta_theta']:.3f} "
              f"A+(40)={c1['t40']['A_plus']:.3f} q_mid(40)={c1['t40']['q_mid']:.4f} "
              f"-> {'PASS' if b1_ok else 'FAIL'}")
    else:
        b1_ok = None
        print("B1 baseline: c1_0 not in this run set")
    c1r = arm('c1_r1')
    if c1r is not None:
        m4_pub = {'A_tot': 1910.93, 'C_abs4': 0.881, 'C_abs40': -0.096}
        r1_ok = (abs(c1r['resonance_t0']['A_tot'] - m4_pub['A_tot']) < 1.0
                 and abs(c1r['summary']['t4']['C_abs'] - m4_pub['C_abs4']) < 0.01
                 and abs(c1r['summary']['t40']['C_abs'] - m4_pub['C_abs40']) < 0.01)
        print(f"B1 c1_r1 (R=1 two-level = m4_2pi5): A_tot="
              f"{c1r['resonance_t0']['A_tot']:.2f} (published 1910.93), "
              f"C_abs 4/40 = {c1r['summary']['t4']['C_abs']:+.3f}/"
              f"{c1r['summary']['t40']['C_abs']:+.3f} (published +0.881/-0.096) "
              f"-> {'PASS' if r1_ok else 'FAIL'}")
    else:
        r1_ok = None
        print("B1 c1_r1: not in this run set")

    # B2: critical height
    print(f"\nB2 critical height at dtheta=pi/5 (C_abs threshold 0.5 at t=40):")
    cabs40 = {}
    mstar = None
    for M in (8, 16, 32):
        a = arm(f'a{M}_pi5')
        if a is None:
            print(f"  M={M:2d}: not in this run set")
            continue
        cabs40[f'a{M}_pi5'] = a['summary']['t40']['C_abs']
        rel = a['resonance_t0']
        rel_ok = rel['floor_ey'] + rel['floor_ei'] < 0.02 * 48 ** 3
        print(f"  M={M:2d}: C_abs(40)={cabs40[f'a{M}_pi5']:+.3f} "
              f"floors={rel['floor_ey'] + rel['floor_ei']:6d} "
              f"min={rel['min_ey']:.4f}/{rel['min_ei']:.4f} "
              f"reliable={rel_ok}")
        if cabs40[f'a{M}_pi5'] >= 0.5 and mstar is None and rel_ok:
            mstar = M
    print(f"  M* = {mstar if mstar else 'NONE (no arm reaches C_abs(40) >= 0.5)'}")

    # B3: factorization at t=0 (two-level arms only: the product law
    # A1(R)*A2(4) applies to the stack-of-stacks; the single-level A arms'
    # resonance law is reported in resonance_t0['ratio_vs_analytic'].
    # The A1 = 0 arms are the B5 domain: the product law predicts 0 and
    # their residue (discrete-grid wobble) is reported there, not here.)
    print(f"\nB3 factorization at t=0 (A_tot vs s_tot*A1(R)*A2(4)):")
    b3_all = True
    b3_rows = []
    for r in runs:
        if r['tag'] in ('c1_0',) or r['tag'].startswith('a'):
            continue
        R = r['n_rungs']
        if r['tag'] == 'c1_r1':
            R = 1
        dth2 = 0.0 if R == 1 else r['phases'][4] - r['phases'][0]
        A1 = A1_factor(R, dth2)
        A2 = 1.0
        rt = r['resonance_t0']
        pred = s_tot * A1 * A2
        if A1 > 1e-9:
            ratio = rt['A_tot'] / max(pred, 1e-30)
            ok = 0.95 <= ratio <= 1.05
            b3_all = b3_all and ok
            b3_rows.append({'tag': r['tag'], 'A1': A1, 'A2': A2,
                            'A_tot': rt['A_tot'], 'pred': pred,
                            'ratio': ratio, 'ok': ok})
            print(f"  {r['tag']:8s}: A_tot={rt['A_tot']:9.2f} "
                  f"pred={pred:9.2f} (A1={A1:.4f}, A2={A2})  "
                  f"ratio={ratio:.5f}  {'PASS' if ok else 'FAIL'}")
        else:
            print(f"  {r['tag']:8s}: A1=0 (B5 domain) — A_tot={rt['A_tot']:.2f} "
                  f"= {rt['A_tot'] / s_tot * 100:.2f}% of s_tot (grid-wobble "
                  f"residue, see B5)")

    # B4: inter-rung persistence ranking
    print(f"\nB4 inter-rung persistence ranking (C_abs at t=4/t=40, "
          f"A_peak ratio t40):")
    rows = []
    for r in runs:
        if r['tag'].startswith('b'):
            s = r['summary']
            rows.append((r['tag'], s['t4']['C_abs'], s['t40']['C_abs'],
                         s['A_peak_ratio_t40'], s['t40']['winding']))
    rows.sort(key=lambda x: -x[2])
    for tag, c4, c40, ar, w in rows:
        print(f"  {tag:8s}: C_abs {c4:+.3f} -> {c40:+.3f} | "
              f"A_peak(40)/A_peak(0)={ar:.3f} | wind(40)={w:+.3f}")
    best = rows[0][0]
    print(f"  best holder: {best}")

    # B5: P_parallel=2 clash
    print(f"\nB5 P_parallel clash (dtheta2=pi, adjacent rungs anti-phase):")
    b5 = {}
    for tag in ('b2_pi', 'b4_pi'):
        r = arm(tag)
        if r is None:
            print(f"  {tag}: not in this run set")
            continue
        rt = r['resonance_t0']
        s = r['summary']
        exact = rt['A_tot'] < 1e-6 * s_tot
        b5[tag] = {'A_tot_0': rt['A_tot'], 'exact_cancellation': exact,
                   'C_abs_0': s['t0']['C_abs'], 'C_abs_4': s['t4']['C_abs'],
                   'C_abs_40': s['t40']['C_abs']}
        print(f"  {tag}: A_tot(0)={rt['A_tot']:.3e} (exact cancellation: "
              f"{exact}) | C_abs 0/4/40 = {s['t0']['C_abs']:+.3f}/"
              f"{s['t4']['C_abs']:+.3f}/{s['t40']['C_abs']:+.3f} | "
              f"A_peak 0/4/40 = {s['t0']['A_peak']:.2f}/"
              f"{s['t4']['A_peak']:.2f}/{s['t40']['A_peak']:.2f}")

    # telemetry
    print(f"\nTelemetry:")
    for r in runs:
        s = r['summary']
        rt = r['resonance_t0']
        print(f"  {r['tag']:8s}: mass drift {s['mass_drift']:.2e} | "
              f"init floors {rt['floor_ey'] + rt['floor_ei']:6d} | "
              f"run-min {s['ey_min']:.4f}/{s['ei_min']:.4f} | NaN "
              f"{s['nan']} | {r['elapsed']:.1f}s")

    results['verdicts'] = {
        'B1_baseline': bool(b1_ok) if b1_ok is not None else None,
        'B1_r1_m4_match': bool(r1_ok) if r1_ok is not None else None,
        'B2_Mstar': mstar,
        'B2_C_abs_40': cabs40,
        'B3_factorization_t0': bool(b3_all),
        'B3_rows': b3_rows,
        'B4_best_holder': best,
        'B4_ranking': [{'tag': t, 'C_abs_4': c4, 'C_abs_40': c40,
                        'A_peak_ratio_40': ar, 'winding_40': w}
                       for t, c4, c40, ar, w in rows],
        'B5_pi_clash': b5,
    }
    with open(f"{rdir}/results.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults: {rdir}/results.json")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--steps', type=int, default=STEPS)
    parser.add_argument('--arm', action='append', default=None)
    parser.add_argument('--init-check', action='store_true',
                        help='build every init, print t=0 resonance, exit')
    parser.add_argument('--from-runs', default=None, metavar='DIR')
    args = parser.parse_args()

    if args.from_runs is not None:
        import glob as _glob
        runs = []
        for f in sorted(_glob.glob(f"{args.from_runs}/run_*.json")):
            d = json.load(open(f))
            runs.append({'tag': d['kind'], 'phases': d['phases'],
                         'rung_of': d['rung_of'], 'elapsed': 0.0,
                         'resonance_t0': d['resonance_t0'],
                         'hist': d['hist'], 'profiles': d['profiles'],
                         'n_layers': d['n_layers'],
                         'n_rungs': d['n_rungs']})
        print(f"Rebuilding from {len(runs)} preserved arms in {args.from_runs}")
        finalize(runs, args.from_runs)
        return

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}  N={T.N}  lam={T.LAM}  t={args.steps * T.DT}")
    arms = build_arms()
    if args.arm is not None:
        arms = [a for a in arms if a[0] in args.arm]
        if not arms:
            raise SystemExit(f"no matching arms in {[a[0] for a in arms]}")
    print(f"Arms: {', '.join(a[0] for a in arms)}")

    rid = datetime.now().strftime("%Y%m%d_%H%M%S")
    rdir = f"runs/{rid}_lattice_stack2"
    os.makedirs(rdir, exist_ok=True)

    if args.init_check:
        for tag, phases, rung_of in arms:
            solver = T.build_solver(device)
            ey_hat, ei_hat, u_hat, zs = stack_init_phases(solver, phases)
            ey = torch.fft.ifftn(ey_hat).real
            ei = torch.fft.ifftn(ei_hat).real
            windows = L1.layer_windows(solver.N, zs, solver.device)
            rt = resonance_t0(solver, ey, ei, windows, zs, phases, 0.0, 0.0)
            print(f"  {tag:8s}: A_tot={rt['A_tot']:10.3f} "
                  f"ratio={rt['ratio_vs_analytic']:.5f} "
                  f"min={rt['min_ey']:.4f}/{rt['min_ei']:.4f} "
                  f"floors={rt['floor_ey']}/{rt['floor_ei']} "
                  f"adv_dev={rt['max_advance_dev']:.4f}")
        print(f"(init check only; {len(arms)} arms)")
        return

    runs = []
    for tag, phases, rung_of in arms:
        solver = T.build_solver(device)          # fresh solver per arm
        r = run_case2(solver, tag, phases, rung_of, rdir, args.steps)
        runs.append(r)
    finalize(runs, rdir)


if __name__ == "__main__":
    main()
