/**
 * NLABridge — Natural Language Autoencoder integration.
 *
 * Wraps the NLA Python inference server to verbalize residual-stream
 * activations (gate vectors, residual norms, layer outputs) into
 * natural language descriptions, and reconstruct vectors from text.
 *
 * Architecture:
 *   Python server (nla_server.py) ← HTTP → NLABridge (TypeScript)
 *
 * Two modes:
 *   AV (verbalizer): vector → text  ("The model thinks X about Y...")
 *   AR (reconstructor): text → vector (planned, not yet served)
 *
 * The AV operates on any d_model-dimensional vector. Gate vectors
 * from the vindex live in the same space as residual-stream activations,
 * making them directly compatible.
 */

import type { ILogger } from '../../../types/interfaces.js'


export interface VerbalizeResult {
  /** The natural language explanation. */
  text: string
  /** Token IDs generated by the AV. */
  tokens: number[]
}

export interface NLAConfig {
  /** URL of the AV Python server. */
  avEndpoint: string
  /** Generation parameters. */
  maxTokens?: number
  temperature?: number
}

const DEFAULT_CONFIG: NLAConfig = {
  avEndpoint: 'http://127.0.0.1:8765',
  maxTokens: 80,
  temperature: 0.0,
}


export class NLABridge {
  private logger: ILogger
  private config: NLAConfig

  constructor(logger: ILogger, config?: Partial<NLAConfig>) {
    this.logger = logger.child ? logger.child('nla-bridge') : logger
    this.config = { ...DEFAULT_CONFIG, ...config }
  }

  /**
   * Verbalize what a vector "means" according to the AV model.
   *
   * Takes any d_model-dimensional Float32Array (gate vector, residual
   * stream activation, layer output) and returns a natural language
   * explanation generated by the NLA activation verbalizer.
   *
   * Returns null when the server is unavailable or the vector is invalid.
   */
  async verbalize(vector: Float32Array): Promise<VerbalizeResult | null> {
    const start = Date.now()
    try {
      const resp = await fetch(`${this.config.avEndpoint}/verbalize`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          vector: Array.from(vector),
          max_tokens: this.config.maxTokens,
          temperature: this.config.temperature,
        }),
        signal: AbortSignal.timeout(30_000),
      })

      if (!resp.ok) {
        const err = await resp.json().catch(() => ({}))
        this.logger.warn('NLA verbalize failed', { status: resp.status, error: err.error })
        return null
      }

      const result = await resp.json() as VerbalizeResult
      this.logger.debug('NLA verbalized', {
        textLen: result.text.length,
        tokens: result.tokens.length,
        durationMs: Date.now() - start,
      })
      return result
    } catch (err) {
      this.logger.debug('NLA server unavailable', { error: String(err) })
      return null
    }
  }

  /**
   * Check if the NLA server is healthy and ready.
   */
  async healthCheck(): Promise<boolean> {
    try {
      const resp = await fetch(`${this.config.avEndpoint}/health`, {
        signal: AbortSignal.timeout(5_000),
      })
      return resp.ok
    } catch {
      return false
    }
  }

  /**
   * Verbalize a gate vector from the vindex.
   *
   * Convenience wrapper that fetches the gate vector for a (layer, feature)
   * pair and verbalizes it. Combines two operations that are often done together
   * in the self-model pipeline.
   */
  async verbalizeGateVector(
    getGateVector: (layer: number, featureIndex: number) => Float32Array | null,
    layer: number,
    featureIndex: number,
  ): Promise<string | null> {
    const vec = getGateVector(layer, featureIndex)
    if (!vec) return null
    const result = await this.verbalize(vec)
    return result?.text ?? null
  }
}
